# Generated by Django 4.2.5 on 2023-10-19 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ContractEmployee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_code', models.AutoField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_dob', models.DateField(blank=True, null=True)),
                ('emp_qualification', models.CharField(blank=True, max_length=20, null=True)),
                ('emp_organization', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_designation', models.CharField(blank=True, max_length=50, null=True)),
                ('emp_basic_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('emp_doj', models.DateField(blank=True, null=True)),
                ('emp_gender', models.CharField(blank=True, max_length=10, null=True)),
                ('emp_address1', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_address2', models.CharField(blank=True, max_length=100, null=True)),
                ('emp_pin_code', models.CharField(blank=True, max_length=20, null=True)),
                ('emp_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('emp_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('emp_esic_enrolled', models.CharField(blank=True, max_length=20, null=True)),
                ('emp_esic_location', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryDetails',
            fields=[
                ('salary_id', models.AutoField(primary_key=True, serialize=False)),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('allowances', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deductions', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ContractEmployee.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('ven_code', models.AutoField(primary_key=True, serialize=False)),
                ('ven_name', models.CharField(max_length=100)),
                ('ven_addr1', models.CharField(blank=True, max_length=100, null=True)),
                ('ven_addr2', models.CharField(blank=True, max_length=100, null=True)),
                ('ven_addr3', models.CharField(blank=True, max_length=100, null=True)),
                ('ven_mob', models.CharField(blank=True, max_length=15, null=True)),
                ('ven_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('ven_adhar', models.CharField(blank=True, max_length=20, null=True)),
                ('ven_bank_det', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='clpaydet',
            name='cl_pay_emp_code',
        ),
        migrations.DeleteModel(
            name='ClEmpDet',
        ),
        migrations.DeleteModel(
            name='ClPayDet',
        ),
        migrations.DeleteModel(
            name='ClVendorInfo',
        ),
        migrations.AddField(
            model_name='employee',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ContractEmployee.vendor'),
        ),
    ]
